### ISSUE TITLE
xcode 14报错

### ISSUE THREAD

**Issue by DeraDream** [0xcj/SectionIndexView#5]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/42810994/189796821-8a3a223e-bbdf-4183-9f57-08f0550c2086.png">

**Comment by DeraDream** [comment]
demo也报相同的错

**Comment by 1401788197** [comment]
hello  问题解决了吗

**Comment by 1401788197** [comment]
> demo也报相同的错

hello 问题解决了吗

**Comment by DeraDream** [comment]
> > demo也报同样的错误
> 
> 你好问题解决了吗

没解决，等作者修复，我回滚13.4.1了

**Comment by nepaul** [comment]
- I have fix it and create a pull  request:
https://github.com/0xcj/SectionIndexView/pull/6

- Repo: https://github.com/nepaul/SectionIndexView

@DeraDream @1401788197
